

seq = str(input())
protein = []
i=0
while i < len(seq)-3:
    if seq[i:i+3] == 'UUU':protein.append('F')
    if seq[i:i+3] == 'UUC':protein.append('F')
    if seq[i:i+3] == 'UUA':protein.append('L')
    if seq[i:i+3] == 'UUG':protein.append('L')
    if seq[i:i+3] == 'UCU':protein.append('S')
    if seq[i:i+3] == 'UCC':protein.append('S')
    if seq[i:i+3] == 'UCA':protein.append('S')
    if seq[i:i+3] == 'UCG':protein.append('S')
    if seq[i:i+3] == 'UAU':protein.append('Y')
    if seq[i:i+3] == 'UAC':protein.append('Y')
    if seq[i:i+3] == 'UAA':break
    if seq[i:i+3] == 'UAG':break
    if seq[i:i+3] == 'UGU':protein.append('C')
    if seq[i:i+3] == 'UGC':protein.append('C')
    if seq[i:i+3] == 'UGA':break
    if seq[i:i+3] == 'UGG':protein.append('W')
    if seq[i:i+3] == 'CUU':protein.append('L')
    if seq[i:i+3] == 'CUC':protein.append('L')
    if seq[i:i+3] == 'CUA':protein.append('L')
    if seq[i:i+3] == 'CUG':protein.append('L')
    if seq[i:i+3] == 'CCU':protein.append('P')
    if seq[i:i+3] == 'CCC':protein.append('P')
    if seq[i:i+3] == 'CCA':protein.append('P')
    if seq[i:i+3] == 'CCG':protein.append('P')
    if seq[i:i+3] == 'CAU':protein.append('H')
    if seq[i:i+3] == 'CAC':protein.append('H')
    if seq[i:i+3] == 'CAA':protein.append('Q')
    if seq[i:i+3] == 'CAG':protein.append('Q')
    if seq[i:i+3] == 'CGU':protein.append('R')
    if seq[i:i+3] == 'CGC':protein.append('R')
    if seq[i:i+3] == 'CGA':protein.append('R')
    if seq[i:i+3] == 'CGG':protein.append('R')
    if seq[i:i+3] == 'AUU':protein.append('I')
    if seq[i:i+3] == 'AUC':protein.append('I')
    if seq[i:i+3] == 'AUA':protein.append('I')
    if seq[i:i+3] == 'AUG':protein.append('M')
    if seq[i:i+3] == 'ACU':protein.append('T')
    if seq[i:i+3] == 'ACC':protein.append('T')
    if seq[i:i+3] == 'ACA':protein.append('T')
    if seq[i:i+3] == 'ACG':protein.append('T')
    if seq[i:i+3] == 'AAU':protein.append('N')
    if seq[i:i+3] == 'AAC':protein.append('N')
    if seq[i:i+3] == 'AAA':protein.append('K')
    if seq[i:i+3] == 'AAG':protein.append('K')
    if seq[i:i+3] == 'AGU':protein.append('S')
    if seq[i:i+3] == 'AGC':protein.append('S')
    if seq[i:i+3] == 'AGA':protein.append('R')
    if seq[i:i+3] == 'AGG':protein.append('R')
    if seq[i:i+3] == 'GUU':protein.append('V')
    if seq[i:i+3] == 'GUC':protein.append('V')
    if seq[i:i+3] == 'GUA':protein.append('V')
    if seq[i:i+3] == 'GUG':protein.append('V')
    if seq[i:i+3] == 'GCU':protein.append('A')
    if seq[i:i+3] == 'GCC':protein.append('A')
    if seq[i:i+3] == 'GCA':protein.append('A')
    if seq[i:i+3] == 'GCG':protein.append('A')
    if seq[i:i+3] == 'GAU':protein.append('D')
    if seq[i:i+3] == 'GAC':protein.append('D')
    if seq[i:i+3] == 'GAA':protein.append('E')
    if seq[i:i+3] == 'GAG':protein.append('E')
    if seq[i:i+3] == 'GGU':protein.append('G')
    if seq[i:i+3] == 'GGC':protein.append('G')
    if seq[i:i+3] == 'GGA':protein.append('G')
    if seq[i:i+3] == 'GGG':protein.append('G')
    i+=3
strprotein = ''.join(protein)
print(strprotein)

